name: Node.js Package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Trigger on semantic versioning tags (e.g., 1.0.0, 1.1.1)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run on main branch
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Update package version
        run: npm version ${{ steps.get_version.outputs.VERSION }} --no-git-tag-version
      
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
